### PR TITLE
Rebuild library to fix crash on MoveNet GPU and enable GPU

### PR DESCRIPTION
**Pull request by vikage**

### CODE REVIEW

**Comment by vikage** [comment]
Fixed #186 #184

**Comment by asus4** [comment]
Thank you @vikage. Can you please tell me which TensorFlow version you have built it with?

**Comment by vikage** [comment]
> Thank you @vikage. Can you please tell me which TensorFlow version you have built it with?

@asus4 I clone the master branch of tensorflow. The last commit at Mon Jan 24 02:29:13. Do we need to build from the release version?

**Comment by vikage** [comment]
@asus4 I was rebuilt tensorflow version 2.7.0.

**Comment by asus4** [comment]
Cool thank you.

**Pull request merged**
